# Generated by Django 6.0 on 2025-12-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default=None, upload_to='artworks/images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artwork',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/previews/'),
        ),
    ]
